### ISSUE TITLE
How to change the background color of the selected text?

### ISSUE THREAD

**Issue by TT5an** [andredelft/typora-tailwind-theme#12]
![image](https://user-images.githubusercontent.com/50618104/218705229-35d1704a-b23d-4e4a-9473-478f4fee2a07.png)
After the text is selected, it cannot be seen clearly in the dark mode.

**Comment by andredelft** [comment]
Hi! Thanks for this suggestion. I have changed the selection background and text color to make sure selected text is better visible.

If you'd like to customize it, you can edit the `--selected-text-bg-color` and `--selected-text-bg-color-dark` variable in your custom CSS

<img width="675" alt="Scherm­afbeelding 2023-04-11 om 15 27 23" src="https://user-images.githubusercontent.com/32297879/231177585-bc906c1b-aeb6-47ca-ad76-1fa39ec44f96.png">
