### ISSUE TITLE
Missing folder from the .zip file? 

### ISSUE THREAD

**Issue by LadislavSzolik** [andredelft/typora-tailwind-theme#6]
Hi @andredelft 
thank you for creating this theme! 

Am I doing something wrong, or the tailwind.zip is missing a folder with fonts?

**Comment by andredelft** [comment]
Ouch, you're completely right, totally forgot about that. Thanks for contacting me, Will update ASAP!

In the meantime, you can also download and install the fonts yourself here: https://rsms.me/inter/

**Comment by andredelft** [comment]
@LadislavSzolik Please check the latest release!

**Comment by LadislavSzolik** [comment]
Thanks :)  I love Tailwind and their color palette. I started to experiment with Typora. Need an editor for Markdown as I write docs with code.
