### ISSUE TITLE
Word wrap not working inside code block

### ISSUE THREAD

**Issue by meichengg** [andredelft/typora-tailwind-theme#8]
Hi, i'm having an issue with your theme, that is word wrap is not working inside code block leading to when i export to a PDF file, it's missing the rest inside the code block as below.

![image](https://user-images.githubusercontent.com/25204246/160983964-1bbb06a4-7fb7-4350-98e3-73b4c243958c.png)

Here, it's missing the last part,

![image](https://user-images.githubusercontent.com/25204246/160984038-a69c87d7-f395-4520-8618-0be6a2108a36.png)

While other themes works just fine with this setting of Typora

![image](https://user-images.githubusercontent.com/25204246/160984150-27b8c7b7-b64a-44ae-a048-730aea3d0bb4.png)

For example, this is 1 line:

![image](https://user-images.githubusercontent.com/25204246/160984339-0af94e50-1b2b-44c2-8932-84bea31610ff.png)

**Comment by andredelft** [comment]
Hi, thanks for submitting this issue! I will delve into it as soon as I can!

**Comment by meichengg** [comment]
Thanks for getting back, i'm waiting for your next update ❤️

**Comment by andredelft** [comment]
Hi @meichengg,

I found the issue: turns out I was overriding some CodeMirror CSS properties that I shouldn't have. Fixed it in my latest release: https://github.com/andredelft/typora-tailwind-theme/releases/tag/v1.1.2

 Best,

André
